name: release
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: bufbuild/buf-setup-action@v1
      - run: pnpm install
      - run: pnpm run gen:es
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "package.json"
          json: >
            {
              "name": "@originpoint-at/candysea-apis",
              "type": "module",
              "version": "${{ steps.package-version.outputs.current-version}}-${{ github.sha }}",
              "peerDependencies": {
                "@bufbuild/protobuf": "^1.4.2"
              }
            }
          dir: 'generated/es'
      - run: cat generated/es/package.json
      - run: tree generated
